POST http://127.0.0.1:3000/v1/user/register HTTP/1.1
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "testtest",
    "password_confirm": "testtest"
}

###
# @name login

GET http://127.0.0.1:3000/v1/user/authenticate HTTP/1.1
Content-Type: application/json
Authorization: Basic admin@example.com:testtest

@authToken = {{login.response.body.$.token}}

###

POST http://127.0.0.1:3000/v1/user/register HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "email": "user@example.com",
    "password": "testtest",
    "password_confirm": "testtest"
}

###

GET http://127.0.0.1:3000/v1/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}